### ISSUE TITLE
rclone install fails 

### ISSUE THREAD

**Issue by dirkpetersen** [dirkpetersen/asm#2]
```
 Installing rclone ... please wait ... Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/asm.py", line 4517, in <module>
    if main():
       ^^^^^^
  File "/home/ec2-user/.local/bin/asm.py", line 52, in main
    subcmd_config(args, cfg, aws)
  File "/home/ec2-user/.local/bin/asm.py", line 153, in subcmd_config
    cfg.copy_binary_from_zip_url(rclone_url, 'rclone',
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/.local/bin/asm.py", line 4387, in copy_binary_from_zip_url
    shutil.copy2(binpath, targetfolder, follow_symlinks=True)
  File "/usr/lib64/python3.11/shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.11/shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
OSError: [Errno 26] Text file busy: '/home/ec2-user/.local/bin/rclone'
```

**Comment by dirkpetersen** [comment]
fixed, was based on sequence of commands
